// <auto-generated />
namespace OneiricGigs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Followe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Followe));
        
        string IMigrationMetadata.Id
        {
            get { return "201706171928185_Followe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
